---
- name: add_mysql_node.yml | Galera Cluster Scaling (add a node)
  hosts: mysql_cluster
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  handlers:
    - ansible.builtin.import_tasks: roles/mysql/handlers/main.yml

  tasks:
  - name: Set global password configuration to 0
    debug:
       msg: innodb_buffer_pool_instances = {{ [1, [((ansible_memtotal_mb * 0.75 / 1024) / 3), 16] | min]|max }}

