---
- name: Import Percona GPG key
  rpm_key:
    key: https://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present
  when: ansible_os_family == "RedHat"

- name: Install
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Enable Percona Tools and Release repositories
  command: percona-release enable-only tools release
  when: ansible_os_family == "RedHat"

- name: Clean dnf cache
  ansible.builtin.command: dnf clean all
  when: ansible_distribution_major_version is version('8', '>=')

- name: Install qpress
  yum:
    name: qpress
    state: present

- name: Install Percona XtraBackup
  yum:
    name: percona-xtrabackup-24
    state: present