---
- name: Import Percona GPG key
  rpm_key:
    key: https://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present
  when: ansible_os_family == "RedHat"

- name: Install
  yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present

- name: Enable Percona Tools and Release repositories
  command: percona-release enable-only tools release
  when: ansible_os_family == "RedHat"

- name: Clean dnf cache
  ansible.builtin.command: dnf clean all
  when: ansible_distribution_major_version is version('8', '>=')

- name: Install qpress
  yum:
    name: qpress
    state: present

- name: Install Percona XtraBackup
  yum:
    name: percona-xtrabackup-24
    state: present

- name: Create "{{ mysql_conf_dir }}" directory
  ansible.builtin.file:
    path: "{{ mysql_conf_dir }}"
    state: directory
  tags: always

- name: Append XtraBackup configuration
  ansible.builtin.template:
    src: xtrabackup.cnf.j2
    dest: "{{ xtrabackup_conf }}"
    owner: mysql
    group: mysql
    mode: '0644'
  tags: always
  