---
# Orchestrator_installation_method: "pip"
- block:
    - name: Install the latest version of Orchestrator
      ansible.builtin.pip:
        name: Orchestrator
        state: latest
        executable: pip3
        extra_args: "--trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org"
        umask: "0022"
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin:/usr/bin"
  when: installation_method == "repo" and Orchestrator_installation_method == "pip"
  environment: "{{ proxy_env | default({}) }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

# Orchestrator_installation_method: "rpm/deb"
- block:
    # Debian
    - name: Install the latest version of Orchestrator packages
      ansible.builtin.package:
        name: "{{ Orchestrator_packages | default('Orchestrator') }}"
        state: latest
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "Debian" and Orchestrator_deb_package_repo | length < 1

    # RedHat
    - name: Install the latest version of Orchestrator packages
      ansible.builtin.package:
        name: "{{ Orchestrator_packages | default('Orchestrator') }}"
        state: latest
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "RedHat" and Orchestrator_rpm_package_repo | length < 1

    # when Orchestrator_deb_package_repo or Orchestrator_rpm_package_repo URL is defined
    # Debian
    - name: Download Orchestrator deb package
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop: "{{ Orchestrator_deb_package_repo | list }}"
      when: ansible_os_family == "Debian" and Orchestrator_deb_package_repo | length > 0

    - name: Install Orchestrator from deb package
      ansible.builtin.apt:
        force_apt_get: true
        deb: "/tmp/{{ item }}"
        state: present
      loop: "{{ Orchestrator_deb_package_repo | map('basename') | list }}"
      register: apt_status
      until: apt_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "Debian" and Orchestrator_deb_package_repo | length > 0

    # RedHat
    - name: Download Orchestrator rpm package
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: /tmp/
        timeout: 60
        validate_certs: false
      loop: "{{ Orchestrator_rpm_package_repo | list }}"
      when: ansible_os_family == "RedHat" and Orchestrator_rpm_package_repo | length > 0

    - name: Install Orchestrator from rpm package
      ansible.builtin.package:
        name: "/tmp/{{ item }}"
        state: present
      loop: "{{ Orchestrator_rpm_package_repo | map('basename') | list }}"
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: ansible_os_family == "RedHat" and Orchestrator_rpm_package_repo | length > 0
  environment: "{{ proxy_env | default({}) }}"
  when:
    - installation_method == "repo"
    - (Orchestrator_installation_method == "rpm" or Orchestrator_installation_method == "deb")
...
