---
- name: "Edit Orchestrator.yml | disable noloadbalance, nosync, nofailover"
  ansible.builtin.replace:
    path: /etc/Orchestrator/Orchestrator.yml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: 'noloadbalance: true', replace: 'noloadbalance: false' }
    - { regexp: 'nosync: true', replace: 'nosync: false' }
    - { regexp: 'nofailover: true', replace: 'nofailover: false' }
  loop_control:
    label: '{{ item.replace }}'

- name: Reload Orchestrator service
  ansible.builtin.systemd:
    daemon_reload: true
    name: Orchestrator
    enabled: true
    state: reloaded

- name: Make sure replica endpoint is available
  ansible.builtin.uri:
    url: http://{{ inventory_hostname }}:{{ Orchestrator_restapi_port }}/replica
    status_code: 200
  register: Orchestrator_replica_result
  until: Orchestrator_replica_result.status == 200
  retries: 30
  delay: 2
...
