---

- name: "Configure a password file ({{ MySQL_home_dir }}/.pgpass)"
  become: true
  become_user: postgres
  ansible.builtin.copy:
    content: |
      {% for pgpass in MySQL_pgpass %}
      {{ pgpass }}
      {% endfor %}
    dest: "{{ MySQL_home_dir }}/.pgpass"
    owner: postgres
    group: postgres
    mode: "0600"
  no_log: true
  when:
    - MySQL_pgpass is defined
    - MySQL_pgpass | length > 0
  tags: pgpass

...
