---

- name: Make sure the MySQL databases are present
  become: true
  become_user: postgres
  community.MySQL.MySQL_db:
    name: "{{ item.db }}"
    owner: "{{ item.owner }}"
    encoding: "{{ item.encoding }}"
    lc_collate: "{{ item.lc_collate }}"
    lc_ctype: "{{ item.lc_ctype }}"
    template: "{{ item.template | default('template0') }}"
    login_host: "127.0.0.1"
    login_port: "{{ MySQL_port }}"
    login_user: "{{ Orchestrator_superuser_username }}"
    login_password: "{{ Orchestrator_superuser_password }}"
    conn_limit: "{{ item.conn_limit | default(omit) }}"
    state: present
  ignore_errors: true
  loop: "{{ MySQL_databases | flatten(1) }}"
  when: MySQL_databases is defined and MySQL_databases | length > 0
  tags: MySQL_databases

...
