---
- name: Ensure MySQL users are present.
  shell: |
    mysql -u root -p'{{ mysql_root_password }}' -e "
    CREATE USER IF NOT EXISTS '{{ item.name }}'@'{{ item.host | default('localhost') }}' IDENTIFIED BY '{{ item.password }}';
    GRANT {{ item.priv | default('*.*:USAGE') }} ON *.* TO '{{ item.name }}'@'{{ item.host | default('localhost') }}';
    FLUSH PRIVILEGES;"
  loop: "{{ mysql_users }}"
  ignore_errors: true
  no_log: true
  when: inventory_hostname == groups['mysql_cluster'][0]
