---

- block:  # RedHat/CentOS
    - name: Add repository
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
        gpgcheck: "{{ item.gpgcheck }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

    # Install Epel Repository
    - name: Remove epel-release package (if exists)
      ansible.builtin.package:
        name: epel-release
        state: absent
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Get epel-release-latest rpm package
      ansible.builtin.get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Install EPEL repository
      ansible.builtin.package:
        name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    # Add repository to install dependencies for mysql
    - block:
        - name: Add MySQL 5.7 community repository
          get_url:
            url: http://repo.mysql.com/yum/mysql-5.7-community/el/8/x86_64/mysql57-community-release-el8-1.noarch.rpm
            dest: /tmp/mysql57-community-release-el8-1.noarch.rpm
          register: mysql_repo

        - name: Install MySQL 5.7 community repository
          yum:
            name: /tmp/mysql57-community-release-el8-1.noarch.rpm
            state: present
          when: mysql_repo is changed

        - name: Disable MySQL 8.0 repository
          ini_file:
            path: /etc/yum.repos.d/mysql-community.repo
            section: mysql80-community
            option: enabled
            value: '0'

        - name: Enable MySQL 5.7 repository
          ini_file:
            path: /etc/yum.repos.d/mysql-community.repo
            section: mysql57-community
            option: enabled
            value: '1'

        - name: Add Galera Cluster repository
          yum_repository:
            name: galera
            description: "Galera Cluster 4 Repository"
            baseurl: "https://releases.galeracluster.com/galera-4/redhat/8/x86_64/"
            gpgkey: "https://releases.galeracluster.com/GPG-KEY-galeracluster.com"
            gpgcheck: yes
            enabled: yes

...
