---
- block: # RedHat/CentOS
    - name: Add repository
      ansible.builtin.yum_repository:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        baseurl: "{{ item.baseurl }}"
        gpgkey: "{{ item.gpgkey }}"
        gpgcheck: "{{ item.gpgcheck }}"
      loop: "{{ yum_repository | flatten(1) }}"
      when: yum_repository | length > 0

    # Install Epel Repository
    - name: Remove epel-release package (if exists)
      ansible.builtin.package:
        name: epel-release
        state: absent
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Get epel-release-latest rpm package
      ansible.builtin.get_url:
        url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        dest: /tmp/
        timeout: 30
        validate_certs: false
      when: install_epel_repo|bool
      tags: install_epel_repo

    - name: Install EPEL repository
      ansible.builtin.package:
        name: "/tmp/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
        disable_gpg_check: true
      register: package_status
      until: package_status is success
      delay: 5
      retries: 3
      when: install_epel_repo|bool
      tags: install_epel_repo

    # Install MySQL Repository
    - block:
        - name: Add Galera repository
          copy:
            dest: "/etc/yum.repos.d/galera.repo"
            content: |
              [galera]
              name = Galera
              baseurl = https://releases.galeracluster.com/galera-3/redhat/8/x86_64/
              gpgkey = https://releases.galeracluster.com/GPG-KEY-galeracluster.com
              gpgcheck = 0

              [mysql-wsrep]
              name = MySQL-wsrep
              baseurl = https://releases.galeracluster.com/mysql-wsrep-5.7/redhat/8/x86_64/
              gpgkey = https://releases.galeracluster.com/GPG-KEY-galeracluster.com
              gpgcheck = 0
      when: install_mysql_repo|bool and ansible_distribution_major_version == '8'
  environment: "{{ proxy_env | default({}) }}"
  when: installation_method == "repo" and ansible_os_family == "RedHat"
  tags: add_repo
