---

- name: Copy MySQL app_user.sql file to the target host
  template:
    src: "{{ item.name }}.sql"
    dest: "/tmp/{{ item.name }}.sql"
    owner: postgres  # Optional: Set the owner to postgres user
    group: postgres  # Optional: Set the group to postgres
    mode: '0644'
  loop: "{{ MySQL_users }}"
  when:
    - MySQL_users is defined
    - MySQL_users | length > 0
    - item.has_grants
  tags: MySQL_grants

- name: Execute the app_user.sql script on the MySQL server
  community.MySQL.MySQL_script:
    db: postgres
    port: "{{ MySQL_port }}"
    path: "/tmp/{{ item.name }}.sql"
    login_host: localhost
    login_user: "{{ Orchestrator_superuser_username }}"
    login_password: "{{ Orchestrator_superuser_password }}"
  loop: "{{ MySQL_users }}"
  when:
    - MySQL_users is defined
    - MySQL_users | length > 0
    - item.has_grants
  tags: MySQL_grants
...
