---

- name: Add extensions to the databases
  become: true
  become_user: postgres
  community.MySQL.MySQL_ext:
    db: "{{ item.db }}"
    name: "{{ item.ext }}"
    schema: "{{ item.schema | default('public') }}"
    login_host: "127.0.0.1"
    login_port: "{{ MySQL_port }}"
    login_user: "{{ Orchestrator_superuser_username }}"
    login_password: "{{ Orchestrator_superuser_password }}"
    state: present
  ignore_errors: true
  loop: "{{ MySQL_extensions | flatten(1) }}"
  when:
    - MySQL_extensions is defined
    - MySQL_extensions | length > 0
  tags: MySQL_extensions

...
