---

# when MySQL NOT exists
- block:
    - name: MySQL | check that data directory "{{ MySQL_data_dir }}" is not initialized
      ansible.builtin.stat:
        path: "{{ MySQL_data_dir }}/PG_VERSION"
      register: pgdata_initialized
      when: Orchestrator_cluster_bootstrap_method == "initdb"

    - name: MySQL | data directory check result
      ansible.builtin.fail:
        msg: "Whoops! data directory {{ MySQL_data_dir }} is already initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - pgdata_initialized.stat.exists
  when:
    - not MySQL_exists | bool
    - not (MySQL_cluster_maintenance|default(false)|bool) # exclude for config_pgcluster.yml

# when MySQL exists
- block:
    - name: MySQL | check that data directory "{{ MySQL_data_dir }}" is initialized
      ansible.builtin.stat:
        path: "{{ MySQL_data_dir }}/PG_VERSION"
      register: pgdata_initialized

    - name: MySQL | data directory check result
      ansible.builtin.fail:
        msg: "Whoops! data directory {{ MySQL_data_dir }} is not initialized"
      when:
        - pgdata_initialized.stat.exists is defined
        - not pgdata_initialized.stat.exists
  when:
    - MySQL_exists | bool
    - not (MySQL_cluster_maintenance|default(false)|bool) # exclude for config_pgcluster.yml
